version: "3"

tasks:
  default:
    deps: [go, swift, php]

  bench:
    deps: [default]
    cmds:
      - hyperfine --warmup 1 go/build/aoc-year2015-day4 swift/.build/release/aoc-year2015-day4 'php php/aoc-year2015-day4/main.php'

  go:
    dir: go
    cmds: [task]

  swift:
    dir: swift
    cmds: [swift build -c release]
