version: "3"

tasks:
  default:
    deps: [go, rust, swift]

  bench:
    deps: [default]
    cmds:
      - hyperfine --warmup 1 \
        go/build/aoc-year2015-day4 \
        'python python/aoc-year2015-day4/main.py' \
        rust/target/release/aoc-year2015-day4 \
        swift/.build/release/aoc-year2015-day4

  go:
    dir: go
    cmds: [task]

  rust:
    dir: rust
    cmds: [cargo build --release]

  swift:
    dir: swift
    cmds: [swift build -c release]
